name: Linters and tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Setup python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install poetry dependencies
        run: poetry install

      - name: Install extra dependencies
        run: python -m pip install --no-use-pep517 lightfm

      - name: Run tests
        run: make test

      - name: Run linters
        run: make lint